# -*- coding: utf-8 -*-
"""Say 1  PRACTICE QUESTIONS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q5uZMso0i0zS67FrfaJUsn7yqFupju8d
"""

import pandas as pd

df=pd.read_csv("/student_performance.csv")

electronics_students = df[df['department'] == 'Electronics']
num_electronics_students = len(electronics_students)
print(f"Number of students from the Electronics Department: {num_electronics_students}")

female_students = df[df['gender'] == 'Female']
average_attendance = female_students['attendance_percentage'].mean()
print(f"Average attendance of female students: {average_attendance_female:.2f}%")

lowest_programming_score_student = df.loc[df['programming_score'].idxmin()]

print(f"Name: {lowest_programming_score_student['name']}")
print(f"Lowest Programming Score: {lowest_programming_score_student['programming_score']}")

students = df[df['math_score'] > 80]
num_students= len(students)
print(f"Number of students who scored above 80 in math: {num_students}")

students_attendance = df[df['attendance_percentage'] > 90]
average_attendance = students_attendance['total_score'].mean()
print(f"Average total score for students with attendance above 90%: {average_attendance:.2f}")

