# -*- coding: utf-8 -*-
"""Day_02_Database_SQL_Visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gW1kwITIlTTfifRkEWTV6KfqXiXHM31K
"""

import sqlite3
#py built in db lib,no pip install needed
import pandas as pd
#for data frame
import matplotlib.pyplot as plt
#plotting submodule for mathplot
import warnings
#subress non critical messge warning
warnings.filterwarnings('ignore')
print("All libraries imported successfully")
print(f"pandas version: {pd.__version__}")
print(f"sqlite3 version: {sqlite3.version}")

df=pd.read_csv('/content/student_performance.csv')

print(f"Dataset loaded: {df.shape[0]} students, {df.shape[1]} columns")
print(f"Columns:{df.columns.tolist()}")
print("\nFirst 3 rows:")
df.head(3)

conn=sqlite3.connect('college.db')
#con=our connection to the  db

cursor=conn.cursor()
df.to_sql(
    'students', #name of the table to create in the db
     conn,   #which db connection in use
     if_exists='replace',
     index=False #do not write df row numbers as a coulumn
)

#verify the table was created
cursor.execute("Select COUNT(*) FROM students")
count = cursor.fetchone()[0]
#.fetchone() retrieves the fisrt result row

print(f"Database 'college.db' created sucessfully")
print(f"Table 'students' has {count} rows")

cursor.execute("PRAGMA table_info(students)")
columns_info = cursor.fetchall()
print("Table structure of 'students':")
print(f"{'Column Name' :<25} {'Data Type' :<12}")
print("-" * 38)
for col in columns_info:
  print(f"{col[1]:<25} {col[2]:<12}")

def run_query(sql,description=""):
  if description:
    print(f"\n{'='*55}")
    print(f" {description}")
    print(f"{'='*55}")
  result=pd.read_sql_query(sql,conn)
  print(result.to_string(index=False))

query1="""
SELECT student_id,name,department,math_score,attendance_percentage
FROM students
LIMIT 10
"""
result1=run_query(query1,"Query 1:First 10 students(SELECT+LIMIT)")

query1="""
SELECT student_id,name,department,math_score,attendance_percentage
FROM students
ORDER BY student_id DESC
LIMIT 5
"""
result1=run_query(query1,"Query 1:Last 5 students(SELECT+LIMIT)")

query1="""
SELECT student_id,name,department,programming_score
FROM students
WHERE programming_score BETWEEN 50 AND 75
ORDER BY student_id
"""
result1=run_query(query1,"Query 1:The List of students between 50 and 75")

query1="""
SELECT *
FROM students
"""
result=run_query(query1)

query3="""
SELECT department From students
GROUP BY department
"""
result1=run_query(query3,"Query")

query_top_scorers = """
SELECT student_id, name, department, programming_score
FROM students
WHERE department IN ('Computer Science', 'Electronics', 'Mechanical')
ORDER BY programming_score DESC, department, name
LIMIT 1
"""

run_query(query_top_scorers, "Top programming scorers from selected departments")

query_low_attendance = """
SELECT student_id, name, department, attendance_percentage
FROM students
WHERE attendance_percentage < 80 AND department != 'Civil'
ORDER BY attendance_percentage DESC
"""

run_query(query_low_attendance, "Students with attendance percentage less than 80 (excluding Civil dept)")

dept_data={

           'data_code':['cs','ec','mech','civil'],
           'dept_name':['Computer Science','Electronics','Mechanical','Civil'],
           'hod_name':['Dr sharma','Dr Ready','Dr patel','Dr Kumar'],
           'established':[1995,1945,1975,1986],
           'intake':[60,60,60,60]
}
dept_df=pd.DataFrame(dept_data)
dept_df.to_sql('departments',conn,if_exists='replace',index=False)
dept_map ={
    'Computer Science':'cs',
    'Electronics':'ec',
    'Mechanical':'mech',
    'Civil':'civil'
}
df['department_code']=df['department'].map(dept_map)
df.head()

query_join="""
SELECT
s.name,
s.math_score,
d.dept_name,
d.hod_name,
d.established
FROM students s
INNER JOIN departments AS d ON s.department=d.dept_name
ORDER BY s.math_score DESC
LIMIT 8
"""
result=run_query(query_join,"Query")



