# -*- coding: utf-8 -*-
"""Day_03_Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X_tY8VSPCO_-Yz6-EsGnKxxMkaZ2-Ei6

# Weather Data ETL Project
"""

import requests
import pandas as pd

API_KEY="0b878f39df4ec71a9ca481eebac79540"

BASE_URL="https://api.openweathermap.org/data/2.5/weather"

cities = [
    "Chennai",
    "Bangalore",
    "Mumbai",
    "Delhi",
    "Hyderabad",
    "Kolkata",
    "Pune",
    "Jaipur",
    "Ahmedabad",
    "Coimbatore"
]

weather_records = []

for city in cities:

    params = {
        'q': city,
        'appid': API_KEY,
        'units': 'metric'
    }

    response = requests.get(BASE_URL, params=params)

    data = response.json()

    if response.status_code == 200:

        weather_records.append({
            'City'        : data.get('name'),
            'Country'     : data.get('sys', {}).get('country'),
            'Temperature' : data.get('main', {}).get('temp'),
            'Feels_Like'  : data.get('main', {}).get('feels_like'),
            'Humidity'    : data.get('main', {}).get('humidity'),
            'Pressure'    : data.get('main', {}).get('pressure'),
            'Weather'     : data.get('weather', [{}])[0].get('main'),
            'Description' : data.get('weather', [{}])[0].get('description'),
            'Wind_Speed'  : data.get('wind', {}).get('speed')
        })

        print(f"Fetched weather data for {city}")

    else:
        print(f"Failed to fetch data for {city}")

raw_df = pd.DataFrame(weather_records)

print("\nRaw Dataset Shape :", raw_df.shape)

print("\nFirst 5 Rows")
print(raw_df.head())

df=raw_df.copy()

df.drop_duplicates(inplace=True)

df['Description'] = df['Description'].fillna('No Description')
df['Weather'] = df['Weather'].fillna('Unknown')

df.columns=(
    df.columns
    .str.strip()
    .str.lower()
)

df = df.apply(
    lambda col: col.str.strip() if col.dtype == 'object' else col
)

# Convert datatypes
df['temperature'] = df['temperature'].astype(float)

df['humidity'] = df['humidity'].astype(int)

print("\nCleaned Dataset Shape :", df.shape)

print("\nMissing Values")
print(df.isnull().sum())

print("\nDuplicate Rows :", df.duplicated().sum())

print("\nFinal Cleaned Dataset")
print(df.head())

output_file = "cleaned_weather_data.csv"

df.to_csv(output_file, index=False)

"""# Employee Salary ETL Project"""

import pandas as pd

raw_df = pd.read_csv('/content/drive/MyDrive/codebooster-datasets/employee_salary_data.csv')

print("\nDataset Shape :", raw_df.shape)

print("\nFirst 5 Rows")
print(raw_df.head())

print("\nColumn Names")
print(raw_df.columns.tolist())

print("\nMissing Values")
print(raw_df.isnull().sum())

print("\nDuplicate Rows :", raw_df.duplicated().sum())

print("\nData Types")
print(raw_df.dtypes)

df=raw_df.copy()

before_rows=len(df)
df.drop_duplicates(inplace=True)
after_rows=len(df)

print(f"\nRows before removing duplicates : {before_rows}")
print(f"Rows after removing duplicates  : {after_rows}")

df['department'] = df['department'].fillna('Unknown')
mean_salary = df['monthly_salary'].mean()
df['monthly_salary'] = df['monthly_salary'].fillna(mean_salary)
print("\nMissing values handled successfully!")

df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

print("\nCleaned Column Names")
print(df.columns.tolist())

df = df.apply(
    lambda col: col.str.strip() if col.dtype == 'object' else col
)

print("\nExtra spaces removed!")

df['monthly_salary'] = df['monthly_salary'].astype(float)

df['yearly_salary'] = df['monthly_salary'] * 12
print("\nYearly Salary Column Added!")

print("\nFinal Cleaned Dataset Shape :", df.shape)

print("\nRemaining Missing Values")
print(df.isnull().sum())

print("\nDuplicate Rows :", df.duplicated().sum())

print("\nFinal Cleaned Dataset")
print(df.head())

output_file = "cleaned_employee_salary.csv"

df.to_csv(output_file, index=False)